### ISSUE TITLE
Print results `check_hmc_diagnostics` in rmarkdown

### ISSUE THREAD

**Issue by Sdemaeyer2** [jpritikin/pcFactorStan#2]
Hi Joshua,

I am in the process of analysing your package and I am currently writing a blog in which I will explore the functionalities further. 

I am using the package `distill` to write my blog. In doing so, I come across peculiar behaviour of the function `check_hmc_diagnostics( )` when I knit my rmarkdown file. The results themselves are not readable in the html file. I do get the titles of the outputs and I also see the results in the console, but they are not printed in the html file. Is that something specific to the implementation of the function or does it have more to do with `distill` do you think?

**Comment by jpritikin** [comment]
`check_hmc_diagnostics` is part of `rstan`. If you look at the man page, you'll find that you can get the results of each test separately. For example, `get_divergent_iterations`, `get_max_treedepth_iterations`, etc. I suggest you use these functions to get the diagnostics a la carte and format them yourself.

**Comment by Sdemaeyer2** [comment]
Great tip! Works perfectly. A big thanks again.
