### ISSUE TITLE
Scale Separation Reliability

### ISSUE THREAD

**Issue by Sdemaeyer2** [jpritikin/pcFactorStan#3]
Hi Joshua

Me again. I have another question. 

In the literature on Comparative Judgement in education scholars are used to report the _Scale Separation Reliability_. The formula is:

SSR = G^2/ (1+G^2) with
G = (True SD) / RMSE

More info on SSR at https://www.cambridgeassessment.org.uk/Images/232694-investigating-the-reliability-of-adaptive-comparative-judgment.pdf

Given that we can estimate the model with pcFactorStan it seems possible to also estimate the SSR (and a posterior for SSR). From each draw we can get the estimated True SD and the RMSE (although I would not know how to get that last one). Would it be possible to integrate this calculation in the generated quantities code block in the Stan code? What would be needed there? I think this is more efficient than doing it afterwards in R. But I lack sufficient skills in Stan to figure out the Stan code here.

Thx to consider helping me out here.

Sven

**Comment by jpritikin** [comment]
You can't do that in the generated quantities block because an estimate of the standard errors are derived from the marginal posteriors. You need to finish sampling before you can estimate the standard errors.

I'm certainly happy to add a function to the package to calculate these statistics from a fitted model. How does this look?

````
library(rstan)
library(pcFactorStan)

dl <- prepData(phyActFlowPropensity[,c(paste0('pa',1:2), 'skill')])
dl$varCorrection <- 5.0

fit1 <- pcStan("unidim_adapt", data=dl)

theta <- summary(fit1, pars=c("theta"), probs=c())$summary
mse <- mean(theta[,'sd']^2)
observedSD <- sd(theta[,'mean'])
trueSD <- sqrt(observedSD^2 - mse)
G <- trueSD / sqrt(mse)
SSR <- G^2 / (1+G^2)
````

**Comment by Sdemaeyer2** [comment]
True. That makes sense of course. The script is easy, but a function is even easier ;-) 
I just ran the calculation for the SSR for the results and I arrive at a value that is really close to the Max Likelihood estimation version! 
I'm finishing a blogpost on the use of your package. Once ready I can send you the link if interested. How to reach you?
Thanks a lot

**Comment by jpritikin** [comment]
> I just ran the calculation for the SSR for the results and I arrive at a value that is really close to the Max Likelihood estimation version!

Nice

> Once ready I can send you the link if interested. How to reach you?

Sure! jpritikin@pobox.com
